version: '3.8'

services:
  db-postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: clean-architecture
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: -path=/migrations/ -database "postgres://user_admin:password_rahasia@db-postgres:5432/clean-architecture?sslmode=disable" up
    depends_on:
      - db-postgres

  clean-architecture-service:
    image: clean-architecture-service:v.1.0.0
    container_name: clean-architecture-service
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=user_admin
      - POSTGRES_PASSWORD=password_rahasia
      - POSTGRES_DBNAME=clean-architecture

volumes:
  postgres_data: